### ISSUE TITLE
How does vertical fade out work?

### ISSUE THREAD

**Issue by amgdeveloper** [FutureMind/recycler-fast-scroll#13]
I've been trying to enable the scroll bar fade out with setScrollbarFadingEnabled(true) and also tried  setScrollBarFadeDuration and setScrollBarDefaultDelayBeforeFade but the scrollbar is never faded out..

**Comment by micHar** [comment]
You are talking about methods specific to `RecyclerView`. These methods apply to the normal scrollbar in the `RecyclerView` and have nothing to do with this library. There are plans, however, to make the fastscroller fading time customisable. The bubble fades out after one second now, Do you also need the handle to fade out? In all implementations I have seen, the handle is always visible.

**Comment by micHar** [comment]
@amgdeveloper You can now provide your own show/hide animations and bubble fade time with `ScrollerViewProvider` and `VisibilityAnimationManager`. Since you only want to change the hiding delay, I suggest extending `DefaultScrollerViewProvider` and  overriding:

 ```
@Override
    public VisibilityAnimationManager provideBubbleVisibilityManager() {
        return new VisibilityAnimationManager.Builder(bubble).withHideDelay(YOUR_DELAY).build();
    }
```

For more info, please, consult the example.
