### ISSUE TITLE
Viewprovider Error 

### ISSUE THREAD

**Issue by Moha6584** [FutureMind/recycler-fast-scroll#24]
in the FastScoller class i keep getting this error

`  viewProvider.setFastScroller(this);`

it says "Setfastscroller in ScrollerviewProvider can not be applied to Fastscroller"

**Comment by micHar** [comment]
Generally - this is a compiler error which tells you, that you're trying to apply a method `setFastScroller` to an instance which doesn't have this method.

Specifically - you're trying to apply a method which doesn't even exist in the whole library to an instance of `ViewProvider` (which should only be used when you're trying to provide your own view for bubble and handle).

Please tell me what you are trying to do so that I can maybe help you. If you just want to run this widget in its simplest form, refer to README or consult example code, please.

**Comment by Moha6584** [comment]
Am trying to use it in a recyclerview populated with sqlite data and am not using any custom bubble or handle i simply copied your code and directly dropped it in my project.
is there any classes i should leave or add?

**Comment by micHar** [comment]
You should not have to call `viewProvider.setFastScroller(this);` manually. Do you have it in your code? What code did you copy? You should probably see https://github.com/FutureMind/recycler-fast-scroll/blob/master/example/src/main/java/com/futuremind/recyclerviewfastscroll/example/fragments/ExampleFragment.java

**Comment by micHar** [comment]
This is not an issue in the library. I can try to help you with your code, but I mark this issue closed.

**Comment by Moha6584** [comment]
am not calling it in anywhere, the classes that i copied to my project the demo are showing that error.
sorry i know you closed it but i dont know how to fix it otherwise

**Comment by micHar** [comment]
You don't have to copy these classes. Just use gradle to import the lib into your project and use it. Everything is in the readme file.
