### ISSUE TITLE
null pointer 

### ISSUE THREAD

**Issue by amansatija** [FutureMind/recycler-fast-scroll#25]
i dont set recycler view in the oncreateview
in on create view i fetch data via async task and then set recycler view 
in this scenarios it says 
nullpointer .. in onLayout when goes it set onTouch listener on handle .hhandle is null ,,??
what is this scene what do i do ??

**Comment by micHar** [comment]
You cannot touch UI from background thread. AsyncTask has onPostExecute method where you should do it. And the recyclerview should be prepared earlier, then you should just load the data to your adapter and call notifyDataSetChanged. You also have to call `fastScroller.setRecyclerView()` AFTER setting the adapter which is clearly stated in the readme. You can post your code, because it's hard to understand what you're trying to do, but nonetheless - this is probably more of a general programming question that you should post on stackoverflow, than an issue of the lib.
