### ISSUE TITLE
scollbar goes behind the system navigation when the root view is CoordinatorLayout

### ISSUE THREAD

**Issue by ohpoloha** [FutureMind/recycler-fast-scroll#30]
is there any fix to do with this issue?

**Comment by micHar** [comment]
Post your layout please

**Comment by ohpoloha** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include layout="@layout/component_tool_bar" />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:transitionName="@string/transition_recyclerview"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    <com.futuremind.recyclerviewfastscroll.FastScroller
        android:id="@+id/fastScroller"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="end"
        android:orientation="vertical"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
</android.support.design.widget.CoordinatorLayout>

```

**Comment by micHar** [comment]
Well, this probably has nothing to do with the lib. CoordinatorLayout works just like a FrameLayout, so  your components are just one over another.

What do you mean by "system navigation" in "scollbar goes behind the system navigation"? The bottom navigation bar with back/home/recent? Maybe you are using some special flags in your styles? You have to post further details, maybe some gists and screenshots, because it's hard to guess what is going on in your app.

**Comment by ohpoloha** [comment]
yes, system navigation is the bar with back/home/recent. I'm using Theme.AppCompat.Light.NoActionBar as my main theme and do not have any special flag. 

i had just one appbar, one recyclerview and one fastscroll. recyclerview has match_parent as height and has no problem at all, but fastscroll is behind the system navigation bar. 

i end up with using relativelayout instead. works fine now :)
