### ISSUE TITLE
how to disable bubble ?

### ISSUE THREAD

**Issue by Hitexroid** [FutureMind/recycler-fast-scroll#35]

**Comment by Hitexroid** [comment]
please help

**Comment by micHar** [comment]
Please, describe the issue. You want to hide it? Set its visibility to gone.

**Comment by Hitexroid** [comment]
Sorry ,i  just want to hide bubble , not handler

**Comment by micHar** [comment]
I am sorry @Hitexroid, but this is just basics of programming and research, you can't expect library developers to solve such problems. Plus you don't really describe what your issue is and I'm lacking mind-reading skills. You want to hide the handle under what circumstances? It auto-hides when you don't scroll it. 

I can see that you are a beginner, so I will try to push you in the right direction. First, you should read the README, then view the sample code and try to implement something on this basis. At the very last, when you have **actually tried** anything on your own and have a specific problem, you can go to stackoverflow.com and ask them for help. But only go there when you have done your research, wrote some code that you can show and describe your issue.
