### ISSUE TITLE
Bug when list have no items

### ISSUE THREAD

**Issue by taynanb** [FutureMind/recycler-fast-scroll#8]
I found a bug when recycler view list adapter is empty.

For solve it, at ScrollListener implementation of FastScroller class, after retrieve first recycler view child:

`View firstVisibleView = recyclerView.getChildAt(0);`

.. Verify if firstVisibleView is null and return without execute rest of method.

```
View firstVisibleView = recyclerView.getChildAt(0);
if(firstVisibleView == null)
    return;
```

This check avoid app's crash!

I hope I helped!

**Comment by micHar** [comment]
The problem is that it should not be visible or operational at all when adapter is empty. I must have tested something and set it to VISIBLE when it really should be GONE.

I think that onScrolled should not be called for an empty recyclerView so it should not be an issue anymore. I applied the fix and uploaded it, please check if it works for you.
